- name: UPDATE hosts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: update system
      ansible.builtin.import_tasks: ../tasks/update.yml

    - name: Prüfen, ob Reboot erforderlich ist
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: System neu starten, wenn nötig
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists