- name: INIT 
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: update system
      ansible.builtin.import_tasks: ../tasks/update.yml

    - name: Root-Dateisystem auf gesamte verfügbare Partition erweitern
      ansible.builtin.command:
        cmd: raspi-config nonint do_expand_rootfs
      become: true  

    - name: Cockpit
      ansible.builtin.import_tasks: ../tasks/setup_cockpit.yml

    - name : USB- und TTY-Einrichtung
      ansible.builtin.import_tasks: ../tasks/setup_usb.yml

    - name: VLANs konfigurieren
      ansible.builtin.import_tasks: ../tasks/setup_vlan.yml
      
    - name: Python
      ansible.builtin.import_tasks: ../tasks/setup_python.yml